### ISSUE TITLE
Slice of primitives as default values

### ISSUE THREAD

**Issue by rednafi** [Burmuley/dysconfig#1]
Thanks for creating the CLI. This is already useful. 

But I was wondering, how this would work if someone wanted to set a slice of integers/floats/complex numbers, slice of strings, or slice of boolean values as a config attribute. 

This is rare I admit but maybe the JSON schema can accept values for different indices if the parent type is a slice `{0: {…}, 1; {…}, …}` and then set the default slice attribute in the `NewConfig` function.

Just a food for thought!

**Comment by Burmuley** [comment]
@rednafi Thanks for your attention to this tiny tool.

Well, if you want to define a slice type, then you can definetely just put `"[]string"` in the `type` parameter of the schema.
But the tricky part is to define `default` value, you're right. Will add some logic to handle this.

**Comment by Burmuley** [comment]
@rednafi check out the PR to address your request: https://github.com/Burmuley/dysconfig/pull/2
Would that do?

**Comment by rednafi** [comment]
Yeah, this is a step towards the right direction. Neat work 🙏🏽
